apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-c-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: service-c
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
