apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: narayanmindire/service-b
          ports:
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          env:
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SERVICE_B_METRICS_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
